talk/objectorientation.tex

- Fix a few typos, reword a few sentences
- Tweak layout and alignments on a few slides
- Use `float` literals instead of `int` to show how it's done
- **Please check this:** Add an `override` on a c++98 slide to give a good example of modern style. Should I update the c++98 label in the top corner?
@sponce

Few improvements for OO part

---

code/functions/Makefile
code/functions/README.md
code/functions/Structs.cpp
code/functions/Structs.h
code/functions/functions.cpp
code/loopsRefsAuto/Makefile
code/loopsRefsAuto/README.md
code/loopsRefsAuto/loopsRefsAuto.cpp
code/smartPointers/smartPointers.cpp
talk/C++Course.tex
talk/basicconcepts.tex

This PR is WIP, since it depends on #2 to be merged.
#2 closed and moved here instead.
- As discussed, the functions part was moved right after pointers and references.
- There's a small exercise for pass by copy / pass by reference
- Some small tweaks / fix typos.
- Added code highlighting to slides where symbolic stacks are shown.
On the slide about arrays and pointers, there was an array cookie/pointer after the array on the symbolic stack. Since this isn't a dynamic allocation, there shouldn't be anything but padding bytes, so I removed it. It won't make a difference for the lecture.
- Following a suggestion from Axel, add a slide about scopes and lifetimes.
- Add exercise about loops, references and auto.

Add slide and about lifetimes, and exercise about loops and references

---

talk/objectorientation.tex

Following @sponce 's "you should not use malloc" this morning.
I realize that in one of the occurrences the `new` is not exactly equivalent to the `calloc`, but I think that zero-initialization of the memory is beyond the example's scope anyway.

Prefer new/delete to malloc/free in example code

---

talk/expert.tex
talk/morelanguage.tex

Use void_t for sfinae example so that we don't fixate on return types. Another option is just adding a `void()` in the end of decltype expr (eg: https://gcc.godbolt.org/z/9qGoe173x)
Also introduce static_assert, I added this in the constexpr section though could make sense only in the expert section. 
Since the material is mostly template meta programming and probably not too relevant feel free to suggest/reject/modify this ;)

add a section on static assert, improve SFINAE with void_t

---

talk/tools.tex

This PR adds two slides about clang-format. It explains how to create a `.clang-format` file, how to run clang-format on a single file with a default style and based on a `.clang-format` file. The PR includes an exercise where the students should format one of the examples with a default style, then create a `.clang-format` file and format multiple files.

Add two slides about clang-format

---

talk/tools.tex

This adds two slides about clang-tidy. It discusses the `compile_commands.json` and the `.clang-tidy` file. It shows how to run `clang-tidy` and the `run-clang-tidy` wrapper scripts. It includes an exercise where the students should generate a `compile_commands.json` file for any exercise and run clang-tidy on it, inspet the output and apply automatic fixes. Then they should revert the changes again.

Add two slides about clang-tidy

---

talk/concurrency.tex

Fix #45.
- Change `lock_guard` mentions to `scoped_lock`.
- Add a slide with best practices (== prefer `scoped_lock`)

Mention scoped_lock instead of lock_guard.

---

talk/C++Course.tex
talk/basicconcepts.tex
talk/concurrency.tex
talk/expert.tex
talk/morelanguage.tex
talk/objectorientation.tex

On first sight, it's easy to miss that `\frametitleii{}` expands to C++98.
Here, I define
```tex
\frametitlecpp[98, 11, 14, ...]{Title}
```
which should be easier to read.
I can offer to run text replacements on all `frametitlexx`.
This could make things such as [#55](https://github.com/hsf-training/cpluspluscourse/pull/55#issuecomment-948361548) a bit easier.

Simplify `\frametitle` commands

---

.gitignore
talk/morelanguage/exceptions.tex

New exceptions section with more illustrative examples
of recommended use. This includes some discussion of
what one should use exceptions for, what one should not
use them for. This includes some performance considerations.
All of the deprecated `throw()` syntax is removed, and
the slide on the more current `nothrow` is expanded.
A few additional LaTeX ephemeral files are added to
.gitignore (arise when processing with MiKTeX).

New exceptions section, recommended modern use

---

talk/morelanguage/morestl.tex

Takes over from #79 See discussions there.
Fixes #69

morestl: add examples for std::optional, any, variant

---

talk/setup.tex

See https://github.com/hsf-training/cpluspluscourse/pull/93#discussion_r813401045
The colour is only for URLs. Intra-document links should not be affected (to be checked when CI finishes).

Colour URLs in hyperref package.

---

talk/C++Course.tex

add a slide on HSF trainings. The only reasonable place I found was right after the intro slide ...

add slides on HSF training

---

talk/objectorientation/constructors.tex

I chose to put them in the constructors section, at the end of C++98 slides, and before C++11 ones. One key question is : should we correct all the subsequent slides with `explicit` ? One one hand, this would be consistent with the advice to use `explicit` by default. On the other hand, it woul dput "noise"in the examples. What do you think ?

Two slides about explicit unary constructors.

---

talk/basicconcepts/coresyntax.tex

A plain `char` type in C++ has an implementation defined sign. e.g., x86 is signed, ARM is unsigned.
See <https://en.cppreference.com/w/cpp/language/types>.
Note that also in English one says "an N bit integer" not "an N bit**s** integer. "bit" here becomes an adjective, so it doesn't matter than there are multiple of them (cf. "an integer of 8 bit**s**", where the plural is correct).

Correct signedness of plain char

---

talk/basicconcepts/arrayspointers.tex
talk/basicconcepts/functions.tex
talk/basicconcepts/scopesnamespaces.tex
talk/setup.tex

As @amadio pointed out, the stacks are showing wrong addresses when
setting word size == 1, but pushing integers on the stack.
There's still a slightly ugly thing: pointers are 32 bits in the current version. I think we can live with that, though. Only to be mentioned if somebody asks.

Fix addresses in memorystack.

---

.github/workflows/builds.yml
code/lambdas/CMakeLists.txt
code/loopsRefsAuto/CMakeLists.txt
code/polymorphism/Makefile
code/templates/Makefile

Taught the CI how to build the exercises on every available (native) platform.
This also revealed problems that I myself made in #119, and which @chavid made in #121. Highlighting that we really desperately need to test these things in the CI. :thinking:
Note that the configuration came out a bit more complicated than I would've hoped. The "matrix" ended up being quite a bit more elaborate than ideal. :frowning: But this was the best that I could come up with after some experimentation.
Note that we should probably also add a test with @chavid's preferred Docker image at one point. (It was you who was looking after running the exercises with Docker, right?) Those we'll need to set up separately. That's why I chose the "native" name for these jobs, following the convention that I used in …

Build the exercises in the CI, master branch (2022.03.14.)

---

.github/workflows/builds.yml
code/python/Makefile

Enabled the build of the Python exercise in the CI. While at the same time greatly simplifying the `Makefile` of the exercise.
This is a follow-up from #129. Pinging @sponce.

Python CI Update, master branch (2022.03.15.)

---

code/smartPointers/CMakeLists.txt
code/smartPointers/smartPointers.cpp
code/smartPointers/solution/smartPointers.sol.cpp
code/stl/CMakeLists.txt
code/stl/Makefile
code/stl/randomize.cpp
code/stl/solution/randomize.sol.cpp

This PR replaces `random_shuffle` (dropped in C++17) by `shuffle` and `accumulate` by `reduce`.
This is not necessary for the exercises tomorrow.

Use shuffle and reduce

---

talk/tools/debugging.tex

Some students yesterday could not run or install gdb on their MacOS. It seems lldb is the only debugger available there.
Also the Intel debugger seems old/deprecated. The new one should be `gdb-oneapi`. But we could also discuss to drop it completely from the slides.

Also advertise lldb and gdb-oneapi

---

.all-contributorsrc
.gitignore
README.md

This adds all contributors to the readme. Closes #54 
I've added everyone but me for `content` now, but I know that some others have also contributed to the infrastructure etc., so you can update that if you want,.
Let's squash the commits.
New people can be added by just commenting somewhere as described [here](https://allcontributors.org/docs/en/bot/overview)

Add allcontributors

---

talk/morelanguage/constexpr.tex

Add more notes and more details on the restrictions in various language standards.
Also start with the C++14 example instead of the C++11 one.

Update constexpr slides

---

talk/objectorientation/advancedoo.tex

This slide was meant to show a scenario where a member function is
overriden. Without virtual this was not the case.
Fixes: #161

Add missing virtual

---

talk/objectorientation/adl.tex
talk/objectorientation/operators.tex

Fix #203 
See also #200 
We are using friends and also hidden friends (+ADL), but it's not explained. I thought we could benefit from one slide on friends related to operators and one for hidden friends as part of ADL.
The first shows up in the essentials, and both show up in the full course.

Hidden friends

---

talk/morelanguage/initialization.tex
talk/morelanguage/morelanguage.tex
talk/objectorientation/constructors.tex

These include scalar, class type, default, value and aggregate initialization.
Aggregate initialization is removed from the constructor discussions.
Fixes: #146, #155

Add slides on initialization

---

talk/objectorientation/inheritance.tex
talk/objectorientation/objectsclasses.tex

In the essentials course, the this pointer created some confusion. The
slide was simplified a bit.
Fix https://github.com/hsf-training/cpluspluscourse/issues/140.

Improve how `this` is presented

---

.github/stale.yml

The stale bot creates a lot of unnecessary noise. Therefore, increase the timeout to one year,
and exempt everything that has an assignee or a milestone from getting touched by the bot.

Reduce stale-bot noise on issues and pull requests

---

talk/introduction/history.tex

Mentioning C++23
Mentioning we are now covering C++20 (or part of it)

Updated history slide

---

code/Makefile
code/header_units/Complex.hpp
code/header_units/Makefile
code/header_units/README.md
code/header_units/main.cpp
code/header_units/solution/Complex.hpp
code/header_units/solution/Makefile
code/header_units/solution/main.cpp
code/modules/Complex.hpp
code/modules/Makefile
code/modules/README.md
code/modules/main.cpp
code/modules/solution/Complex.cpp
code/modules/solution/Makefile
code/modules/solution/main.cpp

This PR adds exercises for header units and modules. Since there is no cmake support for both features yet, I could only add Makefiles for g++.

Add exercises for header units and modules

---

talk/morelanguage/move.tex

It was discussed that the present example might move and RVO nicely.
Therefore, I reworked it to illustrate that it's hard to pass values
into a function nicely.
I tried to show that pass by copy, pass by const ref and pass by ref all have disadvantages.
Fix https://github.com/hsf-training/cpluspluscourse/issues/106.

Rework example code to illustrate need of move.

---

talk/basicconcepts/assert.tex
talk/basicconcepts/functions.tex
talk/basicconcepts/references.tex
talk/basicconcepts/scopesnamespaces.tex
talk/concurrency/mutexes.tex
talk/expert/sfinae.tex
talk/morelanguage/initialization.tex
talk/objectorientation/advancedoo.tex
talk/setup.tex

To continue on #78, here's a draft of a recognisable good practice box. What's missing is the "index of good practices". I need to learn a bit more on the deeper tex mechanics to do this cleanly.
The new environment will in the future "just" create that index automatically.

Good practice

---

talk/expert/variadictemplate.tex

This pattern is just so useful, I wanted to have a slide on it. Also, the pre C++17 workaround is hacky, so I want people to recognize and refactor it when they see it.

Add a slide on folding over comma operator

---

talk/expert/perfectforwarding.tex
talk/expert/variadictemplate.tex

* Split some content into multiple slides and extend
* Add remove_reference_t
* Comment that parenthesis are mandatory in fold expressions

Improve slides on perfect forwarding/variadic templates

---

talk/C++Course.tex
talk/Makefile
talk/setup.tex

Augment the goodpractice environment with automatic entries in the list
of good practices (C++Course.lgp).
The index shows up at the end of the course.
The same technique could be used to generate an index of all exercises (#267).
Regarding @sponce 's comment in #245:
> For good practices, it should not be so difficult. Just follow the example here:
> https://tex.stackexchange.com/questions/564098/how-to-add-include-the-title-of-custom-new-list-of-on-the-toc
> You basically create a new kind of list, here listing the good practices (maybe call it \listgoodpractice and associate a new command \goodpractice which adds to the list and another one \listofgoodpractices which displays the lit, using the \tocfile command form tocloft package.
Then you only have to call \goodpractice in the …

Create an index of good practices

---

.github/workflows/build-slides.yml
.github/workflows/publish-slides.yml
talk/C++Course.tex
talk/Makefile
talk/objectorientation/advancedoo.tex
talk/objectorientation/inheritance.tex
talk/setup.tex

I have contemplated such a refactoring twice now and decided to draft a small prototype now to request some comments.
This PR:
* Add new comment environment advanced
* Replace \ifthenelse by latex built-in \if*** and the advanced comment
environment, because it handles verbatim correctly
* The command to put into onlybasics.tex now changed to \basictrue

Refactor basic/advanced tex file inclusions

---

talk/C++Course.tex
talk/setup.tex

Based on PR #223, changing the formatting of advanced slides is now (almost) trivial. This PR proposes to color advanced slides violet instead of blue.

Use different structure color on advanced slides

---

talk/expert/variadictemplate.tex

We should also show how to use `std::index_sequence` with a lambda, since this use should become more comment as C++20 becomes available.

Add a slide on index_sequence with lambda

---

.github/workflows/build-exercises.yml

To allow compiling c++20 and concepts, try out macos12.
Attempt to fix CI for #261.

Try macos-12 for CI

---

code/ExercisesCheatSheet.md
code/modules/Makefile
code/modules/solution/Complex.cpp

I start to wonder what the goal of the cheatsheet is. IMO it should neither repeat the exercise instructions from the exercise README.md nor the instructions from the slides. What else is left? :)

Add instructions for module and header units exercise to cheatsheet

---

talk/basicconcepts/classenum.tex
talk/basicconcepts/control.tex
talk/basicconcepts/scopesnamespaces.tex
talk/morelanguage/exceptions.tex
talk/objectorientation/typecasting.tex

things like fixing line numbers, missing semi-colon.
Only 2 real changes : 
- constinit slide
- dynamic_cast example

Tiny fixes after rehearsal of advanced course

---

talk/morelanguage/exceptions.tex

But if they do not, they have to terminate.

Nothrow functions don't always handle errors successfully

---

talk/objectorientation/constructors.tex

"force" sounds like `= default` will force the compiler to generate the constructor, which is not the case (the compiler will happily, silently avoid generating a defaulted member function if it would be ill-formed).

Reword default ctor example

---

talk/expert/perfectforwarding.tex

- Remove a wrong statement: rvalues would actually be supported if wrapper took a constT&
- Preserve value type in wrapper function

Minor fixes to perfect forwarding section

---

talk/morelanguage/initialization.tex

- Clarify that only ~~primitive~~ fundamental types can be uninitialized: the previous wording seemed to indicate that any object of a type T that does not have a default constructor can be left uninitialized.
- ~~Remove~~ Reword wrong statement about array initialization

Improve wording about uninitialized values

---

code/condition_variable/condition_variable.cpp
code/condition_variable/solution/condition_variable.sol.cpp
talk/concurrency/atomic.tex
talk/concurrency/condition.tex
talk/concurrency/mutexes.tex
talk/concurrency/threadsasync.tex

Four commits, in order of importance:
- Rework slides on condition_variable.
- Small tweaks in condition_variable exercise.
- Small improvements to concurrency chapter.
- [NFC] Use {} for init and \n for endl in concurrency chapter.

Improvements to concurrency chapter

---

code/variant/solution/variant.sol1.cpp
code/variant/solution/variant.sol2.cpp
code/variant/variant.cpp

- prefer `final` to `virtual` for overrides
- structs inherit publicly by default.
- avoid std::endl in variant exercise, in order to promote best practices, as per C++ core guidelines:
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rio-endl
As an aside, I realize that the purpose of the solution with `get_if` is just to show how `get_if` works, but that code should not pass a code review so I wonder whether it's ok to teach it as a valid solution.

Minor improvements to variant exercise

---

code/templates/CMakeLists.txt
code/templates/Makefile
code/templates/OrderedVector.hpp
code/templates/solution/OrderedVector.sol.hpp

It makes code "more RAII" and removes the need to implement a dtor.
I'd use `make_unique` instead of `new` but the Makefile explicitly builds with `-std=c++11` so I don't have `make_unique`. I don't know if we can bump it to C++14 instead.
I realize that this patch might be controversial for some, but I feel like an advanced C++ course should show that you basically never need to do manual memory management anymore in 2022.

Prefer unique_ptr<T[]> to manual memory management in templates ex

---

talk/concurrency/threadsasync.tex

jthread is mentioned in the slides, but its usage isn't shown. Rectified this here.

Add example with jthread.

---

.github/workflows/build-exercises.yml

It's unclear why every workflow run would run a python setup step, even if no python is used.

Remove python3 workflow action.

---

.github/workflows/build-slides.yml
.gitignore
talk/.latexmkrc
talk/Makefile
talk/basicconcepts/assert.tex
talk/basicconcepts/auto.tex
talk/basicconcepts/control.tex
talk/basicconcepts/functions.tex
talk/basicconcepts/headersinterfaces.tex
talk/basicconcepts/inline.tex
talk/basicconcepts/references.tex
talk/introduction/history.tex
talk/setup.tex
talk/tools/editors.tex
talk/tools/formatting.tex
talk/tools/vcs.tex

I added a `make preview` target to the `Makefile`, which should make it easier to avoid edit compile cycles with an appropriate viewer. On Linux, to use evince as your previewer, add the line below to `~/.latexmkrc`:
```
$pdf_previewer = "start evince"
```
I left it out of the custom config because it's likely different people will want to use different viewers.

Update Makefile to use latexmk, and some minor improvements to the basic concepts section

---

talk/C++Course.tex

This is meant to address #135, at least partially. I've added a few books I thought made sense, and some links to conferences. Let me know which books/links to add/remove, I'm opening this as draft just to get things going. I saw CMake docs were mentioned in the original issue, but I guess we'd need an extra slide, as it didn't really fit with books/conferences. I also wonder if we should have a slide with YouTube channels or not.

Add slides with further resources (books and links to conferences)

---

code/race/Makefile
code/race/README.md
code/race/racing.cpp
code/race/run
code/race/solution/racing.sol.cpp

The race exercise races very infrequently on some platforms. Therefore:
- Provide a variable to spawn more threads
- Provide a run script that invokes the executable until a race occurs
- Add thread sanitizer and valgrind as optional steps to the instructions
Fix #353.

Improve race exercise.

---

talk/morelanguage/lambda.tex

This PR tries to improve what's described in issue #256. However, I am not sure whether this is actually an improvement. I would also be happy with the status quo. @hageboeck you asked for it, your opinion please :)

Replace second python lambda by text

---

code/ExerciseSchedule_AdvancedCourse.md
code/ExerciseSchedule_EssentialCourse.md
code/ExercisesCheatSheet.md

Add clickable links to all exercise directories to schedules and cheatsheet.

Directory links in schedules

---

code/header_units/main.cpp
code/header_units/solution/main.cpp
code/modules/main.cpp
code/modules/solution/main.cpp
code/smartPointers/smartPointers.cpp
code/smartPointers/solution/smartPointers.sol.cpp
code/stl/randomize.cpp
code/stl/solution/randomize.sol.cpp

`std::reduce` can only be used over `std::accumulate` when the binary operation is commutative and associative. This does not hold for the exercises computing squared sums, so `std::reduce` is a bug there.

Use accumulate over reduce when necessary

---

talk/basicconcepts/coresyntax.tex

Not urgent and up for debate.
I would like to replace the "aggressive" red alert boxes by simple comments in the code snippets. Furthermore, all the types mentioned which come from C++ standard headers actually require to be prefixed `std::`. Most compilers allow their use without the namespace though. One argument for the prefix is that such code stops compiling when the `#include <cstdint>` is replaced by `#import std;` (which is why there is `#import std.compat`, preserving the old behavior.).

Remove alert and qualify fixed-width int types

---

talk/basicconcepts/coresyntax.tex

No need to rush this in. I can also explain the situation during the course tomorrow.
This also fixes a small error on the FP slides, where we claim that `3.14F32` is a `float`, which if I read https://wg21.link/P1467 again, is wrong. It is a `std::float32` which is a type distinct from `float`. g++ trunk confirms this: https://godbolt.org/z/TE96bzK7W.
However, the way this works changed a few times during standardization, so I blame noone with getting this wrong :D
Fixes: #213

Add a slide on extended floating-point types

---

code/ExerciseSchedule_EssentialCourse.md
code/polymorphism/Polygons.cpp

The virtual inheritance is less important than the operator exercise, so
the operators should come first.

A few improvements for the OO exercises.

---

code/ExerciseSchedule_EssentialCourse.md
code/ExercisesCheatSheet.md
code/polymorphism/README.md
talk/tools/compiling.tex

~I am really confused now. The slides say the compiler exercise uses the `functions` exercise. But the `polymorphism` exercise has the instructions for the exercise. Which one is not the right one?~
The compiler exercise is now done again on the polymorphism exercise. This was changed in 696cd88 from PR #88 to the functions exercise, so the tools can be discussed even if the OO part was not discussed yet. However, the polymorphism exercise is better since it involves a shared library.

Sync all compiler exercise instructions

---

code/operators/operators.cpp
code/operators/solution/operators.sol.cpp

* provide definition of normalize()
* provide two data members for numerator and denominator
* remove addition operators
* do not check whether *= can be chained

Simplify operators exercise

---

code/Makefile
code/check_setup.sh

Add a script to check your setup for the exercises

---

code/functions/functions.cpp
code/functions/solution/functions.sol.cpp

This PR points out in the instructions of the functions exercise that the solution should only print 5 characters in the end. The solution is adapted with a few alternatives on how to solve this.

Make function exercise print only 5 chars

---

talk/morelanguage/raii.tex
talk/morelanguage/stl.tex
talk/objectorientation/static.tex

- Add extra slide for static members
- Fix a wrong map::insert
- Convert `()` to `{}` for a `std::thread t1{...}`

Small improvements found during JLab course

---

.github/workflows/build-slides.yml
talk/C++Course.tex
talk/Makefile
talk/morelanguage/templates.tex
talk/setup.tex

Here is an attempt at switching between essentials and advanced course without changing files under version control. There is many ways now to switch to essentials:
- Uncomment a line in `C++Course.tex` (but git diff won't be empty)
- `export HEPCPP_ESSENTIALS=1`
`make`
- `make essentials`
- `touch ./buildbasic`
For details, see the code proposed in this PR:
```latex
% There are three ways to switch to the basic course:
% 1. Uncomment the line below. Disadvantage: git diff won't be empty
%\basictrue
% 2. Tell it to the Makefile.
%  2.1 Invoke "make essentials"
%  2.2 export HEPCPP_ESSENTIALS=1
%      make <target>
\ifdefined\makebasic
\basictrue
\fi
% 3. Create a file named ./buildbasic
\IfFileExists{./buildbasic}{\basictrue}
```

Allow for choosing essentials vs full via environment variable.

---

talk/basicconcepts/scopesnamespaces.tex

Add a slide on using namespace std and when not to use it. The slide is at the end of the namespace chapter in the advanced course.
I'm not very sure about the placement of the slide. We have discussed scopes and namespaces, but almost no `std` stuff yet. Also header/implementation haven't been discussed. I tried not to use a lot of `std` knowledge, but it's unavoidable.
Can you think of a location later in the course where this slide would make sense?
Fix #461

Discuss "using namespace std;"

---

talk/objectorientation/advancedoo.tex

I was playing with tikz, and this showed up as error. As far as I can see, the "title" object was removed from that figure.

Fix a tikz positioning directive that points to a non-existing element.

---

talk/C++Course.tex
talk/expert/cpp20concepts.tex

For the next iteration, we want slightly increase the emphasis on c++20. Therefore, the operator <=> moves to the beginning of the expert section.
I also fixed minor typographic issues in the concepts section.

Reorder advanced course

---

exercises/functions/Structs.cpp
exercises/functions/Structs.h

It served no purpose (copy was not slow there, only a sleep made it slow) and was discovered (the hard way) to make windows users having very strange segfaults. Simply because it was too large to be on the stack in such context and was screwing memory !

Dropped useless bigdata member in the functions example

---

talk/basicconcepts/arrayspointers.tex
talk/basicconcepts/control.tex
talk/basicconcepts/headersinterfaces.tex
talk/concurrency/threadsasync.tex
talk/morelanguage/raii.tex
talk/morelanguage/random.tex
talk/morelanguage/stl.tex
talk/objectorientation/advancedoo.tex
talk/objectorientation/allocations.tex
talk/objectorientation/constructors.tex
talk/setup.tex

Extend the discussion of jthread and stop_token as suggested in #272.
As a drive-by improvement, I refactored the goodpractice environment to take optional arguments. Now, only a single command with an optional argument is necessary to pass a shortened title for the index of good practices:
```diff
\end{cppcode}
-  \begin{goodpracticeWithShortcut}{Don't use C's memory management}{C's memory management}
+  \begin{goodpractice}[C's memory management]{Don't use C's memory management}
Use \cppinline{std::vector} and friends or smart pointers
-  \end{goodpracticeWithShortcut}
+  \end{goodpractice}
\end{frame}
```
This stays the same:
```latex
\begin{goodpractice}{Memory management}
```
Fix #272

Add a slide on jthreads and simplify goodpractice environment

---

exercises/constness/Makefile
exercises/constness/constplay.cpp

- Implement the suggestion from #452 
- Fix a few unnecessary `;`
- Add `return 0` to `int main()`
Fix #452.

Refine constplay exercise.

---

exercises/ExerciseSchedule_AdvancedCourse.md
exercises/ubsan/README.md
exercises/ubsan/solution/undefinedBehaviour.cpp
exercises/ubsan/undefinedBehaviour.cpp
talk/tools/sanitizers.tex

Add a bug-ridden program that runs mostly without observable issues, but is full of undefined behaviour.
Using UBSan, all of these issues get revealed at run time.
Fix #243

Add an exercise on UBSan

---

exercises/functions/README.md
exercises/functions/Structs.cpp
exercises/functions/functions.cpp
exercises/functions/solution/functions.sol.cpp

After the functions exercise has been modernised (no arrays, std::string instead), there is no need to print "fiveCharacters". The exercise is about pass by copy vs pass by reference and overloading, so the confusing instructions have been removed.
Fix #426

Make functions exercise less confusing.

---

talk/basicconcepts/headersinterfaces.tex
talk/objectorientation/advancedoo.tex
talk/objectorientation/inheritance.tex
talk/objectorientation/objectsclasses.tex
talk/objectorientation/operators.tex
talk/setup.tex

This is the implementation of many remarks / suggestions made in #428, such as:
- Better explain header/source separation
- Add some code highlights or drawings
- ~~Discuss object slicing~~
- Add possible operator symbols for overloading
- Move `this` slide to a later stage of the OO chapter (and change the confusing code example)
I decided to disregard many comments from #428, because there was no reasonable way to change the slides. These comments referred rather to what we say or questions that the students asked. All the things I did implement are marked with tick boxes, and the things I left out have empty boxes in #428. I don't see a way to do better, so I propose to close the issue after this PR.
Resolves #428

Implement comments from #428

---

exercises/constness/constplay.cpp
talk/tools/debugging.tex

Although the exercise is mostly about battling with the compiler, once people finish this work, they will encounter a crash when running the program.
Here, we init the two pointers to &a and &b to create a runnable program.
@sponce Were the students supposed to fix the crash as well, or should we limit it to "just" compile it and then it should run without errors?

Fix a crash in constplay exercise

---

exercises/basicTypes/README.md
talk/concurrency/condition.tex
talk/concurrency/mutexes.tex
talk/concurrency/threadlocal.tex
talk/morelanguage/lambda.tex
talk/morelanguage/morestl.tex
talk/objectorientation/adl.tex
talk/tools/formatting.tex
talk/tools/webtools.tex

In preparation for the next advanced course, I went through the list of suggestions in #352, and implemented most of them.
A few of these were not relevant enough on second thought, so I propose to close #352 after this PR.
Fix #352.

Fix issue #352

---

talk/morelanguage/morestl.tex

Note that I believe we should make a Chapter from the  "MoreSTL" section. It starts to be too long and with many unrelated points

Added 2 slides on timing at the end of MoreSTL section

---

exercises/ExerciseSchedule_AdvancedCourse.md
talk/C++Course.tex
talk/objectorientation/constructors.tex
talk/setup.tex

It can be difficult to tell the difference between the advanced and essentials slides based on the colour.
Here, we add a little "Adv" in the top right corner.
It currently looks like this (later customisation can be done in `setup.tex` for the command `\frametitlecpp`.

[Advanced] Add a marker on advanced slides.

---

talk/introduction/goals.tex

All main implementation of the languages in the example (Java, C# and Python) are actually compiled to bytecode. IMHO it's better to clearly add explicit statement that C++ is compiled "to native machine code" unlike this languages to avoid ambiguity.

Make explicit statement that C++ compiled "to native machine code"

---

talk/morelanguage/morestl.tex

Hi,
I spotted a typo in the `span` section: exten**d** should be changed to exten**t**.
Cheers.

Fix typo extend -> extent in span section

---

.github/workflows/build-exercises.yml

Macos-12 isn't available, any more.

Upgrade exercise runners to macos-latest.

---

.gitignore
talk/objectorientation/advancedoo.tex
talk/objectorientation/allocations.tex
talk/objectorientation/constructors.tex
talk/objectorientation/operators.tex

- Convert a few constructor calls from `(1, 2)` to `{1, 2}`.
- Add some `explicit` keywords to follow our own recommendations.
- Small typographic refinements

Small refinements for the OO chapter

---

exercises/basicTypes/PrintHelper.h
exercises/basicTypes/basicTypes.cpp
exercises/basicTypes/solution/basicTypes.sol.cpp
exercises/loopsRefsAuto/loopsRefsAuto.cpp
exercises/loopsRefsAuto/solution/loopsRefsAuto.sol.cpp
talk/basicconcepts/classenum.tex
talk/morelanguage/lambda.tex
talk/morelanguage/raii.tex
talk/morelanguage/stl.tex
talk/morelanguage/templates.tex

Running list of improvements from the 12th instalment

Findings from the essentials course
