hsf-training/cpluspluscourse

- code/lambdas/Complex.hpp
- code/lambdas/randomize.cpp
- code/lambdas/solution/randomize.sol.cpp
- code/move/NVector.hpp
- code/move/solution/NVector.sol.hpp
- code/move/solution/trymove.sol.cpp
- code/move/trymove.cpp
- code/python/Complex.hpp
- code/stl/Complex.hpp
- code/stl/randomize.cpp
- code/stl/solution/randomize.sol.cpp
- code/templates/Complex.hpp
- code/templates/OrderedVector.hpp
- code/templates/solution/OrderedVector.sol.hpp
- talk/C++Course.tex
- talk/basicconcepts.tex
- talk/introduction.tex
- talk/objectorientation.tex
> Few fixes found when I gave this course at ESIPAP in February

- code/CMakeLists.txt
- code/ExercisesCheatSheet.md
- code/functions/CMakeLists.txt
- code/functions/Structs.cpp
- code/functions/Structs.h
- code/functions/functions.cpp
- code/loopsRefsAuto/CMakeLists.txt
- CMake integration
- Add a constructor to have the same initialisation syntax for both structs.
- Update exercise cheat sheet.
Ping for @sponce
> CMake integration for 1st day exercises.

- code/functions/Structs.cpp
- talk/basicconcepts.tex
On some platforms, the include was already present, but it was wrong to
leave it out.
@sponce 
Also add small fixes of the slides that became apparent during the lecture.
> Add a missing include.

- code/virtual_inheritance/TextBox.cpp
- code/virtual_inheritance/TextBox.hpp
- talk/basicconcepts.tex
- talk/objectorientation.tex
Best reviewed commit-by-commit. Of course feel free to discard everything or only pick some :)
> Misc. imrpovement suggestions for "basic concepts" and "object orientation" sections

- talk/objectorientation.tex
@sponce 
@roiser
Here are the tweaks for the slides that we discussed during the lecture.
**Note**: This contains the two commits by @roiser from PR #15, because I needed to rebase&merge on top of that.
> Tweaks for second day material.

- talk/objectorientation.tex
I open a PR with some changes we discover during the Aug2021 course lecturing
(sorry my editor removed some trailing spaces, so the first commit is actually more than it really is...)
> some changes during Aug2021 course

- talk/morelanguage.tex
- talk/tools.tex
> Small fixes found during the third-day lecture.

- talk/morelanguage.tex
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution.
To ensure that the right people get notified, you can tag some of the last
contributors with `@githubname`.
Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).
You may delete these instructions from your comment.
\- HSF Training
</details>
> more changes on slides 

- talk/expert.tex
- talk/python.tex
around perfect forwarding and SFINAE
also mentioned latest cppyy version
> Several improvements in the expert and python parts

- README.md
- talk/expert.tex
- talk/python.tex
I have also enabled pre-commit CI, so now this PR should show whether the checks passed or not
> Add pre commit status badge

- talk/morelanguage/morestl.tex
Pure rebase of #55 on top of latest master (modulo the fact that small changes were handled in #74)
> if constexpr first try

- talk/basicconcepts/functions.tex
> add slide on function default arguments

- code/ExercisesCheatSheet.md
- talk/C++Course.tex
- talk/Makefile
- talk/setup.tex
- talk/tools/compiling.tex
by default the full version is created, but setting boolean "onlybasics" to "true" in the main C++Course.tex file changes this.
> Create a "basic" version of this course

- talk/objectorientation/adl.tex
- talk/objectorientation/advancedoo.tex
- talk/objectorientation/constructors.tex
- talk/objectorientation/functors.tex
- talk/objectorientation/inheritance.tex
- talk/objectorientation/objectsclasses.tex
- talk/objectorientation/operators.tex
- talk/setup.tex
I read through the OOP chapter and here are some suggested changes. This PR is not intending to fix critical issues, but rather tries to improve the working, correctness and accuracy in some places. Sometimes I also just liked a different phrasing better. Feel free to comment on any of them!
> Small improvements to the OOP chapter

- talk/basicconcepts/basicconcepts.tex
- talk/basicconcepts/classenum.tex
- talk/basicconcepts/control.tex
- talk/basicconcepts/functions.tex
- talk/basicconcepts/operators.tex
- talk/basicconcepts/scopesnamespaces.tex
I read through the basic chapter and here are some suggested changes.
> Small improvements to the basic chapter

- code/operators/CMakeLists.txt
- code/operators/Makefile
- code/operators/README.md
- code/operators/operators.cpp
- code/operators/solution/operators.sol.cpp
- talk/objectorientation/operators.tex
> Add a new exercise on operators

- code/operators/operators.cpp
- code/operators/solution/operators.sol.cpp
Instead of https://github.com/bernhardmgruber/cpluspluscourse/pull/1
> Extend operators exercise with unit-test-like function

- talk/tools/profiling.tex
- talk/tools/tools.tex
> Add a subsection on profiling with perf/vTune

- code/exercisesIntro.tex
* add Stephan and me as co-authors
* update date
* add that clang tools should be installed
* update download link for exercises
> Update exercise introduction

- .github/workflows/workflow.yml
- talk/C++Course.tex
- talk/Makefile
- Make essentials reachable via makefile
- Add essentials to github builds
> Github actions for essentails version

- talk/basicconcepts/coresyntax.tex
Triggered by PR #116 for which I came too late, I propose some corrections and an additional slide on the basic types.
> Correct and extent slides on basic types

- code/exercisesIntro.tex
- talk/basicconcepts/arrayspointers.tex
- talk/basicconcepts/classenum.tex
- talk/basicconcepts/control.tex
- talk/basicconcepts/coresyntax.tex
- talk/basicconcepts/functions.tex
- talk/basicconcepts/headersinterfaces.tex
- talk/basicconcepts/references.tex
- talk/basicconcepts/scopesnamespaces.tex
- talk/introduction/goals.tex
I went through the first day recording from last year's course and here are a few more improvements for the basic chapter.
> More improvements for the basic course

- .gitignore
- code/control/README.md
- code/control/solution/control.sol.cpp
- code/functions/CMakeLists.txt
- code/functions/Makefile
- code/functions/README.md
- code/functions/functions.cpp
- code/functions/solution/functions.sol.cpp
- code/hello/Makefile
- code/hello/README.md
- code/loopsRefsAuto/CMakeLists.txt
- code/loopsRefsAuto/Makefile
- code/loopsRefsAuto/solution/loopsRefsAuto.sol.cpp
Various modifications done while trying to replay exercises.
> Exercises replay

- README.md
And them to the end of the project README.md .
> Try to track guidelines for exercises

- code/functions/CMakeLists.txt
- code/functions/solution/functions.sol.cpp
@krasznaa could you check that I didn't mess up the CMake?
> Add a solution for functions exercise.

- talk/tools/compiling.tex
> Add two slides on CMake

- talk/basicconcepts/functions.tex
Two small fixes, not pressing for tomorrow.
> Apply two small fixes to basic chapter

- talk/basicconcepts/coresyntax.tex
- talk/basicconcepts/functions.tex
- talk/introduction/goals.tex
- talk/introduction/history.tex
Fixes of things that we found during the lecture.
> First day fixes

- code/control/control.cpp
- code/control/solution/control.sol.cpp
The idea is to have higher chance crashing/having weird values when people do the mistake of thinking that a range based loop gives indices in the local variable. Codes like :
```cpp
for (auto i : numbers) {
auto num = numbers[i];
...
}
```
> Change values in vector of control exercise

- talk/objectorientation/advancedoo.tex
- talk/objectorientation/allocations.tex
- talk/objectorientation/constructors.tex
- talk/objectorientation/static.tex
- talk/tools/compiling.tex
Here are some fixes I made during the morning lecture today.
> Fixes for OO chapter

- code/ExercisesCheatSheet_All.md
- code/ExercisesCheatSheet_TheEssentials.md
I synced the essential and the full cheat sheet. As a drive-by, i fixed #134.
> Sync exercise cheat sheets

- talk/basicconcepts/classenum.tex
- talk/basicconcepts/coresyntax.tex
Fixed some line too long and added ptr to struct in stack when introducing structs
> Small improvements after last session of the course

- code/debug/randomize.cpp
- code/debug/solution/randomize.sol.cpp
- code/polymorphism/solution/trypoly.sol.cpp
- code/polymorphism/trypoly.cpp
Many students had troubles in my afternoon session so I would like to propose the following fixes.
> Improve debug and polymorph exercise

- .github/workflows/builds.yml
* Simplify builds.yml
* Switch to Ubuntu 22.04
* Use g++-11 on Linux builds
> Improve CI

- talk/basicconcepts/basicconcepts.tex
- talk/basicconcepts/inline.tex
> Discuss inline functions and variables

- talk/morelanguage/lambda.tex
> Add a slide on capturing this

- talk/morelanguage/lambda.tex
> Add a slide on generic lambdas, including explicit template parameters

- talk/morelanguage/constexpr.tex
> Add a slide on consteval functions

- talk/tools/doxygen.tex
- talk/tools/tools.tex
> Add slides about doxygen

- talk/objectorientation/advancedoo.tex
Fixes: #99
Also includes a small rewording of the slide on overriding.
> Add slides on virtual destructors

- talk/morelanguage/constexpr.tex
> Add a slide on constinit

- talk/morelanguage/templates.tex
> Add slides on CTAD and deduction guides

- talk/morelanguage/exceptions.tex
Add slides on exception guarantees, standard exceptions and further
resources
Split some slides with too much text and add examples.
Fixes: #162
> Rework and extend exception slides

- talk/tools/sanitizers.tex
> Add slides on TSan and UBsan

- talk/morelanguage/raii.tex
> Use less C in the RAII introduction slides

- code/stl/Complex.hpp
Since I want to use the `Complex` class from the STL exercise in my follow up modules exercises, I refactored the a bit. Primarily, I wanted to make the code shorter and the operators use hidden friends.
> Refactor Complex in STL exercise

- talk/morelanguage/raii.tex
> Little amendment to RAII work

- talk/basicconcepts/arrayspointers.tex
- talk/basicconcepts/classenum.tex
- talk/concurrency/atomic.tex
- talk/concurrency/condition.tex
- talk/concurrency/mutexes.tex
- talk/concurrency/threadsasync.tex
- talk/expert/cpp20concepts.tex
- talk/expert/cpp20spaceship.tex
- talk/expert/perfectforwarding.tex
- talk/expert/sfinae.tex
- talk/expert/variadictemplate.tex
- talk/introduction/history.tex
- talk/morelanguage/initialization.tex
- talk/morelanguage/morestl.tex
- talk/morelanguage/move.tex
- talk/morelanguage/templates.tex
- talk/objectorientation/allocations.tex
- talk/objectorientation/typecasting.tex
- talk/python/marryingcandcpp.tex
- talk/python/modulewriting.tex
I read again through all the slides and here are some small changes I would propose.
> Minor slide improvements

- code/stl/randomize.cpp
- code/stl/solution/randomize.sol.cpp
* Prefix STL calls with std::
* Add const to variables with are not mutated
* Add lambda based alternative solution
> Improve STL exercise

- talk/basicconcepts/assert.tex
- talk/basicconcepts/basicconcepts.tex
- talk/morelanguage/constexpr.tex
Fix #156.
I was unsure as to where to put this. It now sits at the end of basic concepts. Any better ideas?
> Add slides on assertions.

- .github/workflows/slides.yml
- .gitignore
This is a modification of #184.
> Publish slides from CI

- talk/objectorientation/operators.tex
Fixed missing contructor + reduced slightly the font so that it fits in the slide.
> Fixed example code for friend declaration

- README.md
The badges depend on the filenames of the yml files from gh config
> Fix badges for gh actions

- talk/expert/expert.tex
- talk/expert/modules.tex
- talk/setup.tex
This includes:
* motivation for modules
* writing modules
* export
* visibility/reachability
* module structure
* module interface partitions
* module implementation units
* header units
* include translation
* build workflow
* build system challenges
* build system status
* g++ case study
Fixes: #53
> Add slides on modules

- talk/objectorientation/objectsclasses.tex
- talk/tools/sanitizers.tex
Hi @sponce,
here are two fixups to recent PRs that you commented on.
Fix #233.
> Fixup two recent changes

- talk/expert/cpp20spaceship.tex
Made it more compact (8 slides instead of 13) and more straight forward.
Also tried to keep the same style as the rest of the course (less sentences, more sub-bullets mainly)
> Improved operator<=> slides

- talk/morelanguage/morestl.tex
and fixed details on the string_view one
Closes #50
> Added a slide on span

- talk/morelanguage/stl.tex
> Remove slide on deprecated STL binders/adaptors

- talk/morelanguage/lambda.tex
- talk/morelanguage/stl.tex
> Improve lambda slides

- README.md
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.
Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).
You may delete these instructions from your pull request.
\- HSF Training
</details>
> Add list of training events

- talk/C++Course.tex
- talk/morelanguage/constness.tex
- talk/morelanguage/morestl.tex
- talk/morelanguage/ranges.tex
- talk/setup.tex
All comments have been addressed and this is now ready to be merged
Closes #49
> Added slides on C++20 ranges

- talk/concurrency/atomic.tex
> Add slide on `atomic_ref`

- talk/C++Course.tex
- talk/morelanguage/random.tex
- talk/setup.tex
> Add slides on random

- code/CMakeLists.txt
- code/asan/CMakeLists.txt
- code/atomic/CMakeLists.txt
- code/callgrind/CMakeLists.txt
- code/condition_variable/CMakeLists.txt
- code/constness/CMakeLists.txt
- code/control/CMakeLists.txt
- code/cppcheck/CMakeLists.txt
- code/debug/CMakeLists.txt
- code/functions/CMakeLists.txt
- code/helgrind/CMakeLists.txt
- code/hello/CMakeLists.txt
- code/loopsRefsAuto/CMakeLists.txt
- code/memcheck/CMakeLists.txt
- code/modern_oo/CMakeLists.txt
- code/move/CMakeLists.txt
- code/operators/CMakeLists.txt
- code/polymorphism/CMakeLists.txt
- code/race/CMakeLists.txt
- code/smartPointers/CMakeLists.txt
- code/stl/CMakeLists.txt
- code/templates/CMakeLists.txt
- code/valgrind/CMakeLists.txt
- code/virtual_inheritance/CMakeLists.txt
It is the first version that supports C++20, which we use here and there.
> Require at least cmake 3.12

- talk/morelanguage/morestl.tex
* Add an introduction of std::tuple
* Extent structured binding slides
* Introduce tuple-like binding protocol
Fixes: #279
> Add slides on std::tuple and more on structured bindings

- code/operators/README.md
- code/operators/operators.cpp
- code/operators/solution/operators.sol.cpp
Insist on non member operators and use friend (only) when needed
Closes #264
> Improved solution and instructions of operator exercise

- talk/C++Course.tex
- talk/basicconcepts/auto.tex
- talk/basicconcepts/control.tex
- talk/basicconcepts/functions.tex
- talk/concurrency/atomic.tex
- talk/concurrency/condition.tex
- talk/concurrency/mutexes.tex
- talk/morelanguage/constness.tex
- talk/morelanguage/lambda.tex
- talk/morelanguage/move.tex
- talk/morelanguage/raii.tex
- talk/morelanguage/stl.tex
- talk/morelanguage/templates.tex
- talk/objectorientation/advancedoo.tex
- talk/objectorientation/operators.tex
- talk/python/ctypes.tex
- talk/setup.tex
- talk/tools/compiling.tex
- talk/tools/debugging.tex
- talk/tools/formatting.tex
- talk/tools/sanitizers.tex
- talk/tools/staticanalysis.tex
- talk/tools/valgrind.tex
Replicate the work for the `goodpractice` environment to create a list of exercises. The current list is:
**NB**: The "Exercise time" on the left is already fixed.
Do you know of an exercise that I might have missed?
@bernhardmgruber @sponce
> Create index of exercises

- talk/setup.tex
> Reduce font size in list of exercises.

- talk/basicconcepts/arrayspointers.tex
- talk/basicconcepts/control.tex
- talk/basicconcepts/references.tex
- talk/basicconcepts/scopesnamespaces.tex
- talk/expert/coroutines.tex
- talk/expert/cpp20spaceship.tex
- talk/expert/sfinae.tex
- talk/morelanguage/constexpr.tex
- talk/morelanguage/exceptions.tex
- talk/morelanguage/initialization.tex
- talk/morelanguage/raii.tex
- talk/objectorientation/allocations.tex
- talk/tools/valgrind.tex
- talk/tools/vcs.tex
I collected these while I was browsing through the slides to collect if all exercises were collected in #291.
> Various small improvements

- talk/expert/modules.tex
I missed this one in #202 and @hageboeck needs that for his table of exercises in #291.
> Add exercise slide for modules

- .github/workflows/build-exercises.yml
- code/CMakeLists.txt
- code/variadic/CMakeLists.txt
- code/variadic/Makefile
- code/variadic/README.md
- code/variadic/solution/variadic.sol.cpp
- code/variadic/variadic.cpp
- talk/expert/variadictemplate.tex
> Add exercise on variadic templates

- talk/C++Course.tex
- talk/setup.tex
> Automatic update of exercise count on first page now that we have a counter for it

- .github/workflows/build-exercises.yml
- .gitignore
- code/optional/CMakeLists.txt
- code/optional/Makefile
- code/optional/README.md
- code/optional/optional.cpp
- code/optional/solution/optional.sol.cpp
- talk/morelanguage/morestl.tex
> An exercise for std::optional

- talk/basicconcepts/auto.tex
- talk/basicconcepts/control.tex
- talk/concurrency/condition.tex
- talk/concurrency/mutexes.tex
- talk/expert/modules.tex
- talk/expert/variadictemplate.tex
- talk/objectorientation/advancedoo.tex
- talk/setup.tex
Made font smaller and go to 3 columns
Also allowed to have short cuts for exercies name in the list
> Adapted exercise list slide to more exercises

- code/move/solution/trymove.sol.cpp
- code/move/trymove.cpp
Fix an index bug in the move exercise.
Fix #313.
> Fix uniform dist in move exercise

- code/README.md
Extended information on WSL setup.
Added section on using lxplus via ssh.
Added section on Visual Studio.
Separted information on VS Code.
Add information on using VS Code with lxplus.
Previous document: https://docs.google.com/document/d/116zgnclhQDDVW3Lb9alMbCzvsy-NpBKXhMdSO_GVJR4
> Port Windows guide from Google Docs

- talk/objectorientation/adl.tex
> Remove confusing slide on ADL consequences

- talk/basicconcepts/arrayspointers.tex
- talk/basicconcepts/control.tex
- talk/morelanguage/morestl.tex
- talk/morelanguage/raii.tex
- talk/morelanguage/random.tex
- talk/objectorientation/allocations.tex
- talk/setup.tex
- Fixed long titles of exercises
- added a goodpracticeWithShortcut
- Fixed long title for good practices
> Improved layout of indexes

- README.md
There was an outdated link and some missing info on the main README
> Adapt README to advanced course

- talk/C++Course.tex
- talk/basicconcepts/inline.tex
- talk/concurrency/threadlocal.tex
- talk/objectorientation/adl.tex
This is a collections of things we brought up during the lecture.
> Items found on day 1 of advanced course

- talk/morelanguage/copyelision.tex
* Include elision in initialization
* Mention RVO and NRVO
> Extend slides on copyelision

- talk/morelanguage/templates.tex
I know this comes in super late, so feel free to exclude it for tomorrow.
Fixes: #283
> Extend slides on templates

- talk/C++Course.tex
- talk/expert/modules.tex
- talk/morelanguage/constexpr.tex
- talk/morelanguage/constness.tex
- talk/morelanguage/stl.tex
- talk/morelanguage/templates.tex
Small wording and code fixes. And a bit of indentation.
> Small fixes

- talk/morelanguage/templates.tex
Based on a question asked during the essentials course in spring.
> Add slide on class/typename keywords

- talk/concurrency/mutexes.tex
- talk/expert/cpp20concepts.tex
- talk/expert/cpp20spaceship.tex
- talk/expert/sfinae.tex
- talk/morelanguage/lambda.tex
- talk/morelanguage/morestl.tex
- talk/morelanguage/raii.tex
- talk/morelanguage/ranges.tex
> More links to godbolt, cppinsight and cppreference

- .github/workflows/build-exercises.yml
- .github/workflows/build-slides.yml
- .github/workflows/publish-slides.yml
Only run code checks when code/ is touched; latex when talk/ is touched.
> Restrict workflows to subfolders.

- talk/C++Course.tex
- talk/basicconcepts/assert.tex
- talk/concurrency/mutexes.tex
- talk/expert/coroutines.tex
- talk/expert/cpp20concepts.tex
- talk/expert/cpp20spaceship.tex
- talk/expert/sfinae.tex
- talk/expert/variadictemplate.tex
- talk/morelanguage/lambda.tex
- talk/morelanguage/morestl.tex
- talk/morelanguage/raii.tex
- talk/morelanguage/ranges.tex
- talk/setup.tex
And added also an index of godbolt code examples at the end with links both to the slide concerned and to godbolt
> Introduced exampleblockGB environment for examples with godbolt links

- talk/C++Course.tex
- talk/setup.tex
> Add links to YouTube channels of conferences as well

- talk/objectorientation/objectsclasses.tex
> Fix an incorrect return type.

- talk/morelanguage/lambda.tex
namely :
- inverted order of Anatomy and generic lambda slides, as the generic one supposes you know the anatomy
- marked the last 4 slides as advanced
> Tiny changes in lambda chapter

- talk/basicconcepts/arrayspointers.tex
- talk/basicconcepts/auto.tex
- talk/basicconcepts/classenum.tex
- talk/basicconcepts/control.tex
- talk/basicconcepts/headersinterfaces.tex
- talk/introduction/history.tex
- talk/morelanguage/stl.tex
- talk/objectorientation/constructors.tex
- talk/objectorientation/functors.tex
- talk/objectorientation/objectsclasses.tex
- talk/objectorientation/operators.tex
- talk/tools/debugging.tex
- talk/tools/vcs.tex
Here are some suggestions which I collected while reading through the basic course slides again.
Fixes: #218
> Small improvements for basic slides

- code/smartPointers/CMakeLists.txt
- code/smartPointers/Makefile
- code/smartPointers/smartPointers.cpp
- code/smartPointers/solution/smartPointers.sol.cpp
> Remove C-style arrays from smart pointers exercise.

- talk/tools/compiling.tex
Closes #145
I did not address objdump, as this is more advanced and mostly superseeded by godbolt nowadays
> Added 2 slides on nm and ldd in the compilation part

- talk/expert/sfinae.tex
> Better example for usage of enable_if

- talk/tools/debugging.tex
I wonder whether we should include some screenshots of some tools, so people can have a quick feel of what they would get.
Fixes: #394
> Add a slide on debug UIs

- talk/objectorientation/functors.tex
> Replace functor example using inheritance

- talk/morelanguage/stl.tex
- talk/tools/sanitizers.tex
- asan slide. Fix #415 
- STL container slide leaking out of frame
> Two formatting things

- code/README.md
All the tools (except for GUI's like `kcachegrind`) should be available there, even without using an LCG view.
> Advertise lxplus9

- talk/basicconcepts/classenum.tex
- talk/basicconcepts/control.tex
- talk/basicconcepts/functions.tex
- talk/basicconcepts/headersinterfaces.tex
- talk/basicconcepts/operators.tex
Here are a few improvements to the basic chapter.
> Minor improvements to basic chapter

- code/README.md
- code/control/control.cpp
- code/control/solution/control.sol.cpp
- code/functions/README.md
Here are a few small fixes that I collected during the exercises.
> Small exercise fixes

- talk/basicconcepts/arrayspointers.tex
- talk/basicconcepts/auto.tex
- talk/basicconcepts/classenum.tex
- talk/basicconcepts/control.tex
- talk/basicconcepts/operators.tex
- talk/basicconcepts/references.tex
Here are some suggestions for the basics chapter based on the lecture today.
> Improve basic slides

- talk/objectorientation/advancedoo.tex
- talk/objectorientation/allocations.tex
- talk/objectorientation/constructors.tex
- talk/objectorientation/inheritance.tex
- talk/objectorientation/objectsclasses.tex
Here are some suggestions to improve the OO slides.
> Small improvements to OO slides

- talk/objectorientation/advancedoo.tex
- talk/objectorientation/constructors.tex
Draft PR to collect last few fixes.
> Little items for OO chapter

- talk/morelanguage/constness.tex
- talk/morelanguage/exceptions.tex
- talk/morelanguage/lambda.tex
- talk/morelanguage/raii.tex
- talk/morelanguage/stl.tex
- talk/morelanguage/templates.tex
Here are some suggestions to improve the "more language" chapters. I would even argue to rename it, because not a lot there is about "Core modern C++".
> Small improvements for more language chapter

- code/ExerciseSchedule_EssentialCourse.md
- code/ExercisesCheatSheet.md
- code/smartPointers/README.md
- code/smartPointers/smartPointers.cpp
- code/smartPointers/solution/smartPointers.sol.cpp
- talk/morelanguage/raii.tex
Suggest to only work on part 1 and 2 in the essentials course. Part 3 is optional in the essentials.
> Simplify smart pointers exercise for essentials course.

- code/README.md
The README in `code/` was overhauled a bit.
> Update README.md for essentials course at JLab

- code/templates/README.md
- talk/morelanguage/exceptions.tex
- talk/morelanguage/raii.tex
Small items found during lecture.
> Small things during essentials day3

- talk/morelanguage/stl.tex
> Add a slide on unordered_map and hash each

- talk/morelanguage/raii.tex
- talk/objectorientation/constructors.tex
Since this was missed a few times when discussing the rule of 3/5, I concluded we need an extra slide for it.
> Add a slide on the rule of zero

- code/.clang-format
- code/debug/debug.cpp
- code/debug/solution/debug.sol.cpp
- code/valgrind/debug.cpp
- code/valgrind/solution/debug.sol.cpp
Here is a draft of a clang-format style based on WebKit.
I propose to agree on a style and merge the `.clang-format` file without changing every single file immediately.
People editing with clang-format-capable editors will automatically check in formatted code when they work on a file.
After a while, when we are happy with the style it imposes, we can write a loop over all files and create a commit.
Four files have already been formatted using the draft style, see:
- [`debug/debug.cpp`](https://github.com/hsf-training/cpluspluscourse/blob/e5de9717446dc01671579357ac8f3b7802d09bed/code/debug/debug.cpp) and solution
- or `valgrind/debug.cpp` and solution
> Add a clang-format style file.

- code/constness/README.md
- code/constness/constplay.cpp
* Rename functions to more meaningful names
* Extent instructions to tell students to only change lines inside the main function
> Improve clarity of constness exercise

- code/debug/README.md
Students asked me to list the more important commands to solve the debug exercise. Here is what I collected.
How should we best present these? Here in the README.md of the exercise? And what should we do about `lldb`?
> Add some useful gdb commands

- talk/basicconcepts/arrayspointers.tex
- talk/morelanguage/constness.tex
- talk/objectorientation/advancedoo.tex
- talk/objectorientation/allocations.tex
- talk/objectorientation/constructors.tex
- talk/objectorientation/functors.tex
- talk/objectorientation/objectsclasses.tex
> OO fixes after JLab course

- README.md
Added 7th + 8th iterations; also expanded the listed information slightly
> List recent events

- talk/basicconcepts/arrayspointers.tex
- talk/basicconcepts/coresyntax.tex
- talk/basicconcepts/functions.tex
In details :
- fixed indentation in arrayspointers (tabs were present breaking some slides)
- fixed typo in coresyntax comments
- moved "useful aliases" slide to advanced
- tiny improvement in functions (usage of a ref)
> Small corrections found while preparing Machester's course

- .github/workflows/check-links.yaml
- mlc_config.json
To make sure the event links in the readme are ok
> Add markdown link checker

- talk/expert/modules.tex
Fixes: #487 and also contains some updates on the status of module implementations.
> Update module implementation status and fix errors

- talk/basicconcepts/control.tex
- talk/basicconcepts/coresyntax.tex
Here are the fixes we discovered during the autumn 2023 lectures of the advanced course.
> Small fixes for advanced course

- talk/morelanguage/constexpr.tex
- talk/morelanguage/morestl.tex
- talk/morelanguage/templates.tex
includes a move of the `if constexpr` slide from STL to constexpr subchapter
> fixes from 2nd day of Oct 23 session

- talk/tools/debugging.tex
- Add a mention of `gdb$ tui enable` to the slides
> Small corrections after 10th course

- talk/morelanguage/exceptions.tex
> mention std::expected as replacement for exceptions

- talk/morelanguage/exceptions.tex
> Fixed slide on noexcept
